name: secret_workflow_repository

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step with a secret
        run: |
          echo "Hello World"
          echo "This is a secret value: ${{ secrets.SECRET_VALUE }}"
