name: Valid runner
on: [push] 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step 1
        env:
          DAY_OF_WEEK: Sunday
        run: echo "Greetings user. Today is $env:DAY_OF_WEEK!" 
